### ISSUE TITLE
Setup.py is broken

### ISSUE THREAD

**Issue by SamChill** [blha303/getsong#4]
If I try to install via pip (or directly using setup.py) I get the following error:

```
[:~] $ pip install getsong
Downloading/unpacking getsong
  Downloading getsong-v1.1.2.tar.gz
  Running setup.py (path:/tmp/pip_build_chill/getsong/setup.py) egg_info for package getsong
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/tmp/pip_build_chill/getsong/setup.py", line 3, in <module>
        with open("README.rst", "rb") as f:
    IOError: [Errno 2] No such file or directory: 'README.rst'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/tmp/pip_build_chill/getsong/setup.py", line 3, in <module>

    with open("README.rst", "rb") as f:

IOError: [Errno 2] No such file or directory: 'README.rst'
```

**Comment by blha303** [comment]
The PyPI package doesn't include README.rst. I'll fix that right now.
