### ISSUE TITLE
Doesn't work on Python 2

### ISSUE THREAD

**Issue by blha303** [blha303/getsong#5]
Confirmed working on Python 3.

```
$ getsong "kissed a girl"
About to download the audio for Katy Perry - I Kissed A Girl (With Lyrics!), is this correct? [y]
Traceback (most recent call last):
  File "/usr/local/bin/getsong", line 9, in <module>
    load_entry_point('getsong==1.1.3', 'console_scripts', 'getsong')()
  File "/usr/local/lib/python2.7/dist-packages/getsong/getsong.py", line 42, in main
    cont = args.yes or (raw_input(askstr) if hasattr(__builtins__, "raw_input") else input(askstr)).lower() or "y"
  File "<string>", line 0

    ^
SyntaxError: unexpected EOF while parsing
```

**Comment by blha303** [comment]
198174f265055d412cab5fcfd6cb0b6ec020743e

**Comment by blha303** [comment]
Oh well
